repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        exclude: ^app/grpc/recommendations_pb2(_grpc)?\.pyi?$
        additional_dependencies:
          - types-boto3
          - types-requests

  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: pipenv run tests
        language: system
        pass_filenames: false
        always_run: true
