# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import recommendations_pb2 as recommendations__pb2

GRPC_GENERATED_VERSION = "1.82.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in recommendations_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RecommendationsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArtistRelatedArtists = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetArtistRelatedArtists",
            request_serializer=recommendations__pb2.IdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.StringListResponse.FromString,
            _registered_method=True,
        )
        self.GetTrendingArtists = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetTrendingArtists",
            request_serializer=recommendations__pb2.Empty.SerializeToString,
            response_deserializer=recommendations__pb2.StringListResponse.FromString,
            _registered_method=True,
        )
        self.GetArtistTopPicks = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetArtistTopPicks",
            request_serializer=recommendations__pb2.PaginatedIdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.PaginatedStringListResponse.FromString,
            _registered_method=True,
        )
        self.GetLabelRelatedArtists = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetLabelRelatedArtists",
            request_serializer=recommendations__pb2.IdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.StringListResponse.FromString,
            _registered_method=True,
        )
        self.GetLabelTopPicks = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetLabelTopPicks",
            request_serializer=recommendations__pb2.PaginatedIdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.PaginatedStringListResponse.FromString,
            _registered_method=True,
        )
        self.GetReleaseRecommendations = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetReleaseRecommendations",
            request_serializer=recommendations__pb2.IdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.StringListResponse.FromString,
            _registered_method=True,
        )
        self.GetTrendingTracks = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetTrendingTracks",
            request_serializer=recommendations__pb2.Empty.SerializeToString,
            response_deserializer=recommendations__pb2.StringListResponse.FromString,
            _registered_method=True,
        )
        self.GetPlaylistSuggestedTracks = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetPlaylistSuggestedTracks",
            request_serializer=recommendations__pb2.PaginatedIdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.PaginatedStringListResponse.FromString,
            _registered_method=True,
        )
        self.GetUserHome = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetUserHome",
            request_serializer=recommendations__pb2.IdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.StructListResponse.FromString,
            _registered_method=True,
        )
        self.GetUserExplore = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetUserExplore",
            request_serializer=recommendations__pb2.IdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.StructListResponse.FromString,
            _registered_method=True,
        )
        self.GetUserRecommendations = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetUserRecommendations",
            request_serializer=recommendations__pb2.IdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.StructListResponse.FromString,
            _registered_method=True,
        )
        self.GetUserMoreLikeRelease = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetUserMoreLikeRelease",
            request_serializer=recommendations__pb2.IdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.StructListResponse.FromString,
            _registered_method=True,
        )
        self.GetUserMoreLikeArtist = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetUserMoreLikeArtist",
            request_serializer=recommendations__pb2.IdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.StructListResponse.FromString,
            _registered_method=True,
        )
        self.GetUserTopPicks = channel.unary_unary(
            "/ufb_recommendations.v1.RecommendationsService/GetUserTopPicks",
            request_serializer=recommendations__pb2.IdRequest.SerializeToString,
            response_deserializer=recommendations__pb2.StructListResponse.FromString,
            _registered_method=True,
        )


class RecommendationsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetArtistRelatedArtists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTrendingArtists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetArtistTopPicks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetLabelRelatedArtists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetLabelTopPicks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetReleaseRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTrendingTracks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPlaylistSuggestedTracks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUserHome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUserExplore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUserRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUserMoreLikeRelease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUserMoreLikeArtist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUserTopPicks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RecommendationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetArtistRelatedArtists": grpc.unary_unary_rpc_method_handler(
            servicer.GetArtistRelatedArtists,
            request_deserializer=recommendations__pb2.IdRequest.FromString,
            response_serializer=recommendations__pb2.StringListResponse.SerializeToString,
        ),
        "GetTrendingArtists": grpc.unary_unary_rpc_method_handler(
            servicer.GetTrendingArtists,
            request_deserializer=recommendations__pb2.Empty.FromString,
            response_serializer=recommendations__pb2.StringListResponse.SerializeToString,
        ),
        "GetArtistTopPicks": grpc.unary_unary_rpc_method_handler(
            servicer.GetArtistTopPicks,
            request_deserializer=recommendations__pb2.PaginatedIdRequest.FromString,
            response_serializer=recommendations__pb2.PaginatedStringListResponse.SerializeToString,
        ),
        "GetLabelRelatedArtists": grpc.unary_unary_rpc_method_handler(
            servicer.GetLabelRelatedArtists,
            request_deserializer=recommendations__pb2.IdRequest.FromString,
            response_serializer=recommendations__pb2.StringListResponse.SerializeToString,
        ),
        "GetLabelTopPicks": grpc.unary_unary_rpc_method_handler(
            servicer.GetLabelTopPicks,
            request_deserializer=recommendations__pb2.PaginatedIdRequest.FromString,
            response_serializer=recommendations__pb2.PaginatedStringListResponse.SerializeToString,
        ),
        "GetReleaseRecommendations": grpc.unary_unary_rpc_method_handler(
            servicer.GetReleaseRecommendations,
            request_deserializer=recommendations__pb2.IdRequest.FromString,
            response_serializer=recommendations__pb2.StringListResponse.SerializeToString,
        ),
        "GetTrendingTracks": grpc.unary_unary_rpc_method_handler(
            servicer.GetTrendingTracks,
            request_deserializer=recommendations__pb2.Empty.FromString,
            response_serializer=recommendations__pb2.StringListResponse.SerializeToString,
        ),
        "GetPlaylistSuggestedTracks": grpc.unary_unary_rpc_method_handler(
            servicer.GetPlaylistSuggestedTracks,
            request_deserializer=recommendations__pb2.PaginatedIdRequest.FromString,
            response_serializer=recommendations__pb2.PaginatedStringListResponse.SerializeToString,
        ),
        "GetUserHome": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserHome,
            request_deserializer=recommendations__pb2.IdRequest.FromString,
            response_serializer=recommendations__pb2.StructListResponse.SerializeToString,
        ),
        "GetUserExplore": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserExplore,
            request_deserializer=recommendations__pb2.IdRequest.FromString,
            response_serializer=recommendations__pb2.StructListResponse.SerializeToString,
        ),
        "GetUserRecommendations": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserRecommendations,
            request_deserializer=recommendations__pb2.IdRequest.FromString,
            response_serializer=recommendations__pb2.StructListResponse.SerializeToString,
        ),
        "GetUserMoreLikeRelease": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserMoreLikeRelease,
            request_deserializer=recommendations__pb2.IdRequest.FromString,
            response_serializer=recommendations__pb2.StructListResponse.SerializeToString,
        ),
        "GetUserMoreLikeArtist": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserMoreLikeArtist,
            request_deserializer=recommendations__pb2.IdRequest.FromString,
            response_serializer=recommendations__pb2.StructListResponse.SerializeToString,
        ),
        "GetUserTopPicks": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserTopPicks,
            request_deserializer=recommendations__pb2.IdRequest.FromString,
            response_serializer=recommendations__pb2.StructListResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ufb_recommendations.v1.RecommendationsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "ufb_recommendations.v1.RecommendationsService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RecommendationsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetArtistRelatedArtists(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetArtistRelatedArtists",
            recommendations__pb2.IdRequest.SerializeToString,
            recommendations__pb2.StringListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTrendingArtists(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetTrendingArtists",
            recommendations__pb2.Empty.SerializeToString,
            recommendations__pb2.StringListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetArtistTopPicks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetArtistTopPicks",
            recommendations__pb2.PaginatedIdRequest.SerializeToString,
            recommendations__pb2.PaginatedStringListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetLabelRelatedArtists(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetLabelRelatedArtists",
            recommendations__pb2.IdRequest.SerializeToString,
            recommendations__pb2.StringListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetLabelTopPicks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetLabelTopPicks",
            recommendations__pb2.PaginatedIdRequest.SerializeToString,
            recommendations__pb2.PaginatedStringListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetReleaseRecommendations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetReleaseRecommendations",
            recommendations__pb2.IdRequest.SerializeToString,
            recommendations__pb2.StringListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTrendingTracks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetTrendingTracks",
            recommendations__pb2.Empty.SerializeToString,
            recommendations__pb2.StringListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPlaylistSuggestedTracks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetPlaylistSuggestedTracks",
            recommendations__pb2.PaginatedIdRequest.SerializeToString,
            recommendations__pb2.PaginatedStringListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserHome(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetUserHome",
            recommendations__pb2.IdRequest.SerializeToString,
            recommendations__pb2.StructListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserExplore(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetUserExplore",
            recommendations__pb2.IdRequest.SerializeToString,
            recommendations__pb2.StructListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserRecommendations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetUserRecommendations",
            recommendations__pb2.IdRequest.SerializeToString,
            recommendations__pb2.StructListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserMoreLikeRelease(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetUserMoreLikeRelease",
            recommendations__pb2.IdRequest.SerializeToString,
            recommendations__pb2.StructListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserMoreLikeArtist(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetUserMoreLikeArtist",
            recommendations__pb2.IdRequest.SerializeToString,
            recommendations__pb2.StructListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserTopPicks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ufb_recommendations.v1.RecommendationsService/GetUserTopPicks",
            recommendations__pb2.IdRequest.SerializeToString,
            recommendations__pb2.StructListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
